export const SubredditsList = () => 
  [
    "gifs",
    "chemicalreactiongifs",
    "anime",
    "minecraft",
    "eldenring",
    "darksouls3",
    "darksouls2",
    "cyberpunk",
    "witcher3",
    "deadspace",
    "crushcrush",
    "genshinimpact",
    "honkaistarrail",
    "overwatch",
    "ocean",
    "sea",
    "fish",
    "underwater",
    "subnautica",
    "landscape",
    "terraria",
    "stardewvalley",
    "skyrim",
    "finalfantasyxv",
    "everlastingsummer",
    "metroexodus",
    "horses",
    "cats",
    "dogs",
    "helltaker",
  ];

export const RandomSubreddit = () => SubredditsList()[Math.floor(Math.random()*SubredditsList().length)];